language: python
python:
    - "3.6"

install:
      pip install codecov tox-travis

script:
    - tox -e flake8
    - tox -e isort
    - tox -e py27
    - tox
after_success:
    - codecov -t 076aff3c-4061-42da-90a8-31f441e00220
